# Generated by Django 4.1 on 2023-08-08 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pssapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobEntry",
            fields=[
                ("sr_no", models.AutoField(primary_key=True, serialize=False)),
                ("job_name", models.CharField(max_length=100)),
                ("job_code", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="JobDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=30)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pssapp.jobentry",
                    ),
                ),
            ],
        ),
    ]
