# Generated by Django 4.1 on 2023-08-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pssapp", "0002_jobentry_jobdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplications",
            fields=[
                ("application_id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=254)),
                ("PhoneNo", models.CharField(max_length=20)),
                ("Resume", models.FileField(upload_to="uploads/")),
            ],
        ),
    ]
