# Generated by Django 4.1 on 2023-08-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pssapp", "0003_jobapplications"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplications",
            name="jobname",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="jobapplications",
            name="Email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="jobapplications",
            name="Name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="jobapplications",
            name="PhoneNo",
            field=models.CharField(default="", max_length=20),
        ),
    ]
