# Generated by Django 4.1 on 2023-08-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pssapp", "0004_jobapplications_jobname_alter_jobapplications_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplications",
            name="jobname",
        ),
        migrations.AddField(
            model_name="jobapplications",
            name="Jobname",
            field=models.CharField(default="", max_length=300),
        ),
    ]
