# Generated by Django 4.1 on 2023-08-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pssapp", "0005_remove_jobapplications_jobname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplications",
            name="Jobname",
        ),
        migrations.AddField(
            model_name="jobapplications",
            name="Job_name",
            field=models.CharField(default="", max_length=300),
        ),
    ]
